---
# Configure gunicorn 

- name: Create gunicorn log directory
  file: path=/var/log/gunicorn state=directory

- name: Create gunicorn log files
  file: path={{ item }} state=touch
  with_items:
    - /var/log/gunicorn/access.log
    - /var/log/gunicorn/error.log

- name: Copy gunicorn systemd script
  template: src=./docker_rest_web.service.j2 dest=/etc/systemd/system/docker_rest_web.service
  notify:
      - Restart gunicorn
