version: '2'
services:
  web:
    image: docker.io/jartamon/docker-rest-web:latest
    command: /usr/bin/gunicorn --bind 0.0.0.0:8000 docker-rest-web:app
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8000:8000
    environment:
      - APP_NAME=docker-rest-web
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - L_SERVER=192.168.33.60,192.168.33.70
      - DEF_PROTOCOL=tcp
      - DOCKER_PORT=2375
      - DEF_REG_NAME=docker.io
      - DEF_REP_NAME=jartamon
      - DEF_IMAGE_NAME=python-ping
      - DEF_IMAGE_VERSION:latest
      - DEF_CONTAINER_NAME:ping
      - DEF_CONTAINER_PORT=5001
      - DEF_PATH=ping
      - DEF_REPLICA_NUMBER=2
      - DEF_REDIS_URL=redis://web-redis:6379/0
    restart: always
  web-redis:
    image: redis:5.0.3-alpine
