# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
  {
    :id => "1",
    :name => "web01_v1",
    :box => "bento/ubuntu-16.04",
    :ip => '192.168.33.50',
    :cpus => "1",
    :memory => "512"
  },
  {
    :id => "2",
    :name => "web02_v1",
    :box => "bento/ubuntu-16.04",
    :ip => '192.168.33.60',
    :cpus => "2",
    :memory => "512"
  },
  {
    :id => "3",
    :name => "web03_v1",
    :box => "bento/ubuntu-16.04",
    :ip => '192.168.33.70',
    :cpus => "1",
    :memory => "512"
  },
]

Vagrant.configure("2") do |config|
  boxes.each do |box|
    config.vm.define box[:name] do |vmn|
      vmn.vm.box = box[:box]
      vmn.vm.provider "virtualbox" do |vb|
        vb.memory = box[:memory]
        vb.cpus = box[:cpus]
      end

      #vmn.vm.network "forwarded_port", guest: 8080, host: 8080 
      vmn.vm.network "private_network", ip: box[:ip]
      #vmn.vm.synced_folder "./data", "/vagrant_data"
      vmn.vm.provision "shell", inline: <<-SHELL
        set -e
        apt-get update
        apt-get install curl
        echo "Install Docker"
        curl -fsSL get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker vagrant
      SHELL
    end
  end
end

