# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

 config.vm.define "web_v1" do |web_v1|
  web_v1.vm.box = "bento/ubuntu-16.04"
 
  web_v1.vm.provider "virtualbox" do |vb|
   vb.memory = "512"
   vb.cpus = 1
  end

  web_v1.vm.network "forwarded_port", guest: 8080, host: 8080 
  web_v1.vm.network "private_network", ip: "192.168.33.50"
  #web_v1.vm.synced_folder "./data", "/vagrant_data"
  web_v1.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt-get install curl
   echo "Install Docker"
   curl -fsSL get.docker.com -o get-docker.sh
   sudo sh get-docker.sh
   sudo usermod -aG docker vagrant
  SHELL
 end 

end

