---
# Install docker_rest_web

# Synchronize source code when not deploying to vagrant
# - name: Sync source code
#  when: not vagrant_box
#  synchronize: src={{ user_src_path }} dest=/opt/www delete=yes

- name: Install dependencies
  apt: name="{{ item }}" state=present
  with_items:
    - python-pip

- name: Install docker
  pip: name="{{ item }}" state=present
  with_items:
    - docker
    - docker-compose

#- name: Pull docker-rest-web image
#  docker_image: name=jartamon/docker-rest-web repository=docker.io tag=latest

- name: Create src folder
  file: path=/tmp/src state=directory

- name: Get docker-compose file
  get_url: url="https://raw.githubusercontent.com/yart76/docker-rest-web/master/svc/web/docker-compose-web-prod.yml" dest=/tmp/src/docker-compose.yml

- name: Pull images
  docker_service: project_src=/tmp/src pull=yes state=present
